name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Extract version
      id: package_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Build
      run: |
        npm install
        npm run build
      env:
        VITE_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        VITE_APP_VERSION: ${{ env.VERSION }}
        
    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages

